os: linux
dist: bionic
language: node_js
node_js:
- 10

env:
- SOLIDITY_COVERAGE=true

script:
- set -e
- npm run lint
- npm test

before_deploy: npm run build

deploy:
  provider: npm
  email: devops@windingtree.com
  api_token:
    secure: ZLM3bxeg7FvJmzHNEEUle198H6Fc+Gb7YxJ5gRSkr7O8Z0E6C89LFtnwUpxH2cmqqC7iUoLh8W1ksbV7lmR/JAqu7Le7sCLilzVzEfxaLEVEAxjMEBgiJ2BjbfD18Ekdjoa1fvwIEFKAiT2qy448Khr2GcBCEX4OFGmUYkbm3zdYWp1PRdpgWF7KRSqsDZWTnHSPRBA26u4NnvvbipDwDYKWVBC7P2VcbMDT8sIQUgG+TWc9niEVSp5iRimHa443WKUNgOQyE4vfKRFeg55ndi5rck12qlMCvs+/PVTVRUyXDATnrzelpubaQQnC7khdXry4kOcDfkm7xoaOAglDxPPddqteRo0s0cHyUl09AKTNVu7GVDMhiqVsnnf/FuRtuOHGxb5P8zbHnWWNrQ5dK7rvw1veJRr6roAgFGakq8dqoUWv48GVxWxp7kvauikU1vM8+a1gxMrjrTn4WEGYErhhv7GBgzBbQXSvzeaO7IVG5RoBhgkGdjCiKylMUNgxnfteFLC4/fmUTV5982aJ7JHT3aAsZY2o5T5ruCbJpOltXlNYpXwn3tIfdfYVjtUPylg+ytpaqvtPGpYyHGCVu4NEdx5o+1nmXCDpRYxuRPiIoYiQC/4lQ3eoWT7Vz2RMUx2Rq5VoTIsVDEXc38mrUAJxmsV2jmte8MuOcdQng54=
  on:
    repo: windingtree/wt-contracts
    tags: true

notifications:
  slack:
    secure: 54YpZzt/Y4H0qfdqdwRw23O5FukjOmboMUHMCgArPGfGfl9o/gFPepbH35gYLNuG6ZY510swZ4AVDvKHR02ZaU67gO7YasMp1eqENbjpxKhaiDCNjidks8tt8+VIB/I2+KzTDwF6mfIHElRIC0Iglhh7T2YBGsF2Gze9XKWkBWxsCv3vwYWEpJ85MkrfjtCwLDjKHlAdNyhzO8eRnFCZV6rYtZGp9gwkyu7O1NBrfls4ThjmOWRztB9gTP7CR/RfmD/qasfGdcL+43sx6ChMElolThMjX9eFWIBPk7xZj0Eu453hgTrM2UCT3YNwYc9xH9LpuI5e06CdRW7XqoAz8VgggE5liyMp4OQVL+kV/Ad1pljMyKeTLf7CVY9c1DFvBWgdFSyeWXcgAu1pJ/3iQ+8wcVvLfRbj/J2m0SnrZUOgBK0iCoVZkoPvbkUDAOLjipszCBZ2P6KQx2ACuwLsE94rJiKIpBbvKw8n7ltepZ4dK6ssA39PXdCeHDvZCX/6hjFWVtDfayDD4UD6Mwn5FyL/wLhSqjJ6A8qgNIc/+UrOeO25H9UdvHZPuu2BuIttp6TEHaZ/WADYWbUUat4JEtIYA2H038pNy8oNRve/oA8rkt2todNeXzr0NTvjcMcGVTKvvGC2vcUiMQlXuJLlvgX8ZXAZLQBbr5lr+PbtMSI=
